[TC-1821][TC-1877] Allow all spree version between 3.2.0 and 5.0
TerraCycle/spree_events_tracker pull request #1
Opened 2019-10-30 13:02 UTC by erik-terracycle

2019-10-30 13:56 UTC, storhet approved these changes

2019-10-30 14:20 UTC, SkayHUN approved these changes

2019-10-30 15:13 UTC, AHolcsik approved these changes

2019-11-04 11:38 UTC, emanreyalp approved these changes

2019-11-04 13:31 UTC, adamFoldvari approved these changes

2019-11-14 12:54 UTC, SkayHUN approved these changes

2019-11-14 14:30 UTC, adamFoldvari approved these changes

2019-11-14 14:58 UTC, AHolcsik approved these changes

2019-11-14 14:58 UTC, VasiliyMaksymov approved these changes

2019-11-18 08:56 UTC, bluta requested changes

2019-11-18 08:56 UTC, bluta commented on app/models/concerns/spree/order_contents_decorator.rb
> -module Spree
what happened with this functionality?

2019-11-19 13:17 UTC, bluta approved these changes

2019-11-19 13:17 UTC, merged